### ISSUE TITLE
Recherche bibliographique sur les methodes de lecture de marquages

### ISSUE THREAD

**Issue by AurelienmartW** [datalab-mi/Basegun-ml#4]
Dans le but de develloper un module de lecture de marquage, il est nécéssaire d'effectuer une veille technologique sur les derniers modèles d'OCR.

### Tasks

- [x] Explorer les derniers modèles d'OCR
- [x] Comparer les différents modèles identifiés selon des critères de performance, rapidité, et des exigences fonctionnelles et techniques définies
- [x] Définir une shortloist des modèles les plus adaptés au cas d'usage
- [x] Tester en profondeur les différents modèles de la shortlist avec des images de type naturabuy (plus proche de la realité Basegun)
- [x] Arbitrer sur le choix d'un modèle pour l'implémentation du module de lecture

**Comment by AurelienmartW** [comment]
### Tesseract:
**Issues**: 

- detection si texte ne ressort pas assez
- Detection mots plutot que caractères

**Pistes**:

- detection text in natural scene
- passage à v3 tesseract plutot que V4 pour avoir de la character recognition
- Utilisation d'autre modèle OCR -> easy OCR

	
### Easy OCR:
Premiers résultats intéréssants
Bonne lecture
**Issues**:

- Temps inférence un peu long

**Pistes**:

- Resize images en entrée
- prétraitement d'image
- ajouter une tolérance d'erreur ?? (sur tout, sur certains mots ?)

**Comment by ClemGerard** [comment]
Présentation le 30/04 des pistes/resultats/avantages/inconvénients.
